sampletable: 'sampletable.tsv'
assembly: 'dm6'

# If not specified here, use the environment variable REFERENCES_DIR.
# references_dir:

aligner:
    index: 'hisat2'
    tag: 'r6-11'

rrna:
    index: 'bowtie2'
    tag: 'rRNA'

gtf:
    tag: "r6-11"

kallisto:
    tag: "r6-11_transcriptome"


# references has the structure:
#
#   assembly:           [ used as top-level dir for references ]
#     tag:              [ user-defined; often indicates version or release ]
#       type:           [ must be either "gtf" or "fasta" ]
#         url:          [ string or list of urls ]
#         postprocess:  [ string of importable function or dict of function and args ]
#         conversions:  [ list of gtf conversions; only if type == gtf ]
#         indexes:      [ list of indexes to build; only if type == fasta ]

references:

  sacCer3:
    default:
      fasta:
        url: 'http://hgdownload.cse.ucsc.edu/goldenPath/sacCer3/bigZips/chromFa.tar.gz'
        postprocess: 'postprocess.sacCer3.fasta_postprocess'
        indexes:
            - 'bowtie2'

  dm6:
    r6-11:

      gtf:
        url: 'ftp://ftp.flybase.net/genomes/Drosophila_melanogaster/dmel_r6.11_FB2016_03/gtf/dmel-all-r6.11.gtf.gz'
        postprocess: "postprocess.dm6.gtf_postprocess"
        conversions:
          - 'refflat'

      fasta:
        url: 'ftp://ftp.flybase.net/genomes/Drosophila_melanogaster/dmel_r6.11_FB2016_03/fasta/dmel-all-chromosome-r6.11.fasta.gz'
        postprocess: "postprocess.dm6.fasta_postprocess"
        indexes:
          - 'bowtie2'
          - 'hisat2'

    r6-11_transcriptome:
      fasta:
        url: 'ftp://ftp.flybase.net/genomes/Drosophila_melanogaster/dmel_r6.11_FB2016_03/fasta/dmel-all-transcript-r6.11.fasta.gz'
        indexes:
          - 'kallisto'

    rRNA:
      fasta:
        url:
          - 'https://www.arb-silva.de/fileadmin/silva_databases/release_128/Exports/SILVA_128_LSURef_tax_silva_trunc.fasta.gz'
          - 'https://www.arb-silva.de/fileadmin/silva_databases/release_128/Exports/SILVA_128_SSURef_Nr99_tax_silva_trunc.fasta.gz'
        postprocess:
            function: 'common.filter_fastas'
            args: 'Drosophila melanogaster'
        indexes:
            - 'hisat2'
            - 'bowtie2'

  hg19:
    gencode-v19:
      fasta:
        url: 'ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_19/GRCh37.p13.genome.fa.gz'
        indexes:
          - 'bowtie2'
          - 'hisat2'
      gtf:
        url: 'ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_19/gencode.v19.annotation.gtf.gz'

    gencode_v19_plus_lncRNA_transcriptome:
      fasta:
        url:
          - 'ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_19/gencode.v19.pc_transcripts.fa.gz'
          - 'ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_19/gencode.v19.lncRNA_transcripts.fa.gz'
        postprocess: "common.cat"
        indexes:
          - 'kallisto'

  ecoli:
    default:
      fasta:
        url: 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/845/GCF_000005845.2_ASM584v2/GCF_000005845.2_ASM584v2_genomic.fna.gz'
        indexes:
          - 'bowtie2'

  wolbachia:
    default:
      fasta:
        url: 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/008/025/GCF_000008025.1_ASM802v1/GCF_000008025.1_ASM802v1_genomic.fna.gz'
        indexes:
          - 'bowtie2'

  dicty:
    ensembl_2.7.33:
      gtf:
        url: 'ftp://ftp.ensemblgenomes.org/pub/release-33/protists/gtf/dictyostelium_discoideum/Dictyostelium_discoideum.dicty_2.7.33.gtf.gz'
        conversions:
          - 'refflat'

    ensembl_transcriptome_2.7:
      fasta:
        url:
            - "ftp://ftp.ensemblgenomes.org/pub/protists/release-33/fasta/dictyostelium_discoideum/cdna/Dictyostelium_discoideum.dicty_2.7.cdna.all.fa.gz"
            - "ftp://ftp.ensemblgenomes.org/pub/protists/release-33/fasta/dictyostelium_discoideum/ncrna/Dictyostelium_discoideum.dicty_2.7.ncrna.fa.gz"
        postprocess: "common.cat"
        indexes:
            - "kallisto"

    ensembl_2.7:
      fasta:
        url: 'ftp://ftp.ensemblgenomes.org/pub/protists/release-33/fasta/dictyostelium_discoideum/dna/Dictyostelium_discoideum.dicty_2.7.dna_sm.toplevel.fa.gz'
        indexes:
            - 'bowtie2'
            - 'hisat2'
    rRNA:
      fasta:
        url:
            - 'https://www.arb-silva.de/fileadmin/silva_databases/release_128/Exports/SILVA_128_LSURef_tax_silva_trunc.fasta.gz'
            - 'https://www.arb-silva.de/fileadmin/silva_databases/release_128/Exports/SILVA_128_SSURef_Nr99_tax_silva_trunc.fasta.gz'
        indexes:
            - 'hisat2'
            - 'bowtie2'
        postprocess:
            function: 'common.filter_fastas'
            args: 'Dictyostelium discoideum'
