__default__:
  prefix: "--gres=lscratch:20 --time=4:00:00"

bowtie2_index:
  prefix: "--gres=lscratch:20 --time=4:00:00 --mem=32g"

hisat2_index:
  prefix: "--gres=lscratch:20 --time=4:00:00 --mem=32g"

hisat2:
  prefix: "--gres=lscratch:20 --time=4:00:00 --mem=32g"

fastq_screen:
  prefix: "--gres=lscratch:20 --time=4:00:00 --mem=32g"

markduplicates:
  prefix: "--gres=lscratch:20 --time=4:00:00 --mem=32g"

collectrnaseqmetrics:
  prefix: "--gres=lscratch:20 --time=4:00:00 --mem=32g"

salmon_index:
  prefix: "--mem=32g"

salmon:
  prefix: "--mem=32g"

bigwig_neg:
  prefix: "--gres=lscratch:20 --mem=16g"

bigwig_pos:
  prefix: "--gres=lscratch:20 --mem=16g"

star:
  prefix: "--time=8:00:00 --mem=64g"

ngm:
  prefix: "--time=8:00:00 --mem=64g"
