# sampletable: TSV file defining sample metadata.
#
# First column must have header name "samplename".
sampletable: 'config/sampletable.tsv'

# sample_dir: directory in which each sample is expected to have its own
# directory and fastq file[s]. If `sampletable` lists a sample with samplename
# SAMPLE1, then at least the file $sample_dir/SAMPLE1/SAMPLE1_R1.fastq.gz is
# expected.
sample_dir: 'data/rnaseq_samples'

# Directory to contain reports and other aggregations
aggregation_dir: 'data/aggregation'

# Which key in the `references` dict below to use
assembly: 'dmel'

# If not specified here, use the environment variable REFERENCES_DIR.
# references_dir:

aligner:
    index: 'hisat2'
    tag: 'r6-16'

rrna:
    index: 'bowtie2'
    tag: 'rRNA'

gtf:
    tag: "r6-16"

kallisto:
    tag: "r6-16_transcriptome"


# references has the structure:
#
#   assembly:           [ used as top-level dir for references ]
#     tag:              [ user-defined; often indicates version or release ]
#       type:           [ must be either "gtf" or "fasta" ]
#         url:          [ string or list of urls ]
#         postprocess:  [ string of importable function or dict of function and args ]
#         conversions:  [ list of gtf conversions; only if type == gtf ]
#         indexes:      [ list of indexes to build; only if type == fasta ]

references:

  sacCer3:
    default:
      fasta:
        url: 'http://hgdownload.cse.ucsc.edu/goldenPath/sacCer3/bigZips/chromFa.tar.gz'
        postprocess: 'lib.postprocess.sacCer3.fasta_postprocess'
        indexes:
            - 'bowtie2'

  dmel:
    rRNA:
      fasta:
        url:
          - 'https://www.arb-silva.de/fileadmin/silva_databases/release_128/Exports/SILVA_128_LSURef_tax_silva_trunc.fasta.gz'
          - 'https://www.arb-silva.de/fileadmin/silva_databases/release_128/Exports/SILVA_128_SSURef_Nr99_tax_silva_trunc.fasta.gz'
        postprocess:
            function: 'lib.common.filter_fastas'
            args: 'Drosophila melanogaster'
        indexes:
            - 'hisat2'
            - 'bowtie2'

    r6-11:
      gtf:
        url: 'ftp://ftp.flybase.net/genomes/Drosophila_melanogaster/dmel_r6.11_FB2016_03/gtf/dmel-all-r6.11.gtf.gz'
        postprocess: "lib.postprocess.dm6.gtf_postprocess"
        conversions:
          - 'refflat'
          - gffutils: # kwargs below will be provided to `gffutils.create_db`
              merge_strategy: 'merge'
              id_spec:
                  transcript: ['transcript_id', 'transcript_symbol']
                  gene: ['gene_id', 'gene_symbol']
              gtf_transcript_key: 'transcript_id'
              gtf_gene_key: 'gene_id'
              disable_infer_genes: True

          # the attribute from the GTF to consider gene ID
          - genelist:
              gene_id: 'gene_id'

          - annotation_hub:
              ahkey: 'AH49581'
              keytype: 'ENSEMBL'

      fb_annotation:
        url: 'ftp://ftp.flybase.net/releases/FB2016_03/precomputed_files/genes/fbgn_annotation_ID.tsv.gz'
        postprocess: "lib.postprocess.dm6.fb_annotation_postprocess"

      fb_synonym:
        url: 'ftp://ftp.flybase.net/releases/FB2016_03/precomputed_files/synonyms/fb_synonym_fb_2016_03.tsv.gz'
        postprocess: "lib.postprocess.dm6.fb_synonym_postprocess"

      fasta:
        url: 'ftp://ftp.flybase.net/genomes/Drosophila_melanogaster/dmel_r6.11_FB2016_03/fasta/dmel-all-chromosome-r6.11.fasta.gz'
        postprocess: "lib.postprocess.dm6.fasta_postprocess"
        indexes:
          - 'bowtie2'
          - 'hisat2'

    r6-11_transcriptome:
      fasta:
        url: 'ftp://ftp.flybase.net/genomes/Drosophila_melanogaster/dmel_r6.11_FB2016_03/fasta/dmel-all-transcript-r6.11.fasta.gz'
        indexes:
          - 'kallisto'

    r6-11_and_ercc:
      gtf:
        url:
          - 'ftp://ftp.flybase.net/genomes/Drosophila_melanogaster/dmel_r6.11_FB2016_03/gtf/dmel-all-r6.11.gtf.gz'
          - 'https://www-s.nist.gov/srmors/certificates/documents/SRM2374_Sequence_v1.FASTA'
        postprocess:
          function: "lib.postprocess.merge.file_merge"
          args:
            - "lib.postprocess.dm6.gtf_postprocess"
            - "lib.postprocess.ercc.gtf_postprocess"
        conversions:
          - 'refflat'
          - 'gffutils'

      fasta:
        url:
          - 'ftp://ftp.flybase.net/genomes/Drosophila_melanogaster/dmel_r6.11_FB2016_03/fasta/dmel-all-chromosome-r6.11.fasta.gz'
          -  'https://www-s.nist.gov/srmors/certificates/documents/SRM2374_Sequence_v1.FASTA'
        postprocess:
          function: "lib.postprocess.merge.file_merge"
          args:
            - "lib.postprocess.dm6.fasta_postprocess"
            - "lib.postprocess.ercc.fasta_postprocess"
        indexes:
          - 'bowtie2'
          - 'hisat2'

    r6-16:
      gtf:
        url: 'ftp://ftp.flybase.net/genomes/Drosophila_melanogaster/dmel_r6.16_FB2017_03/gtf/dmel-all-r6.16.gtf.gz'
        postprocess: "lib.postprocess.dm6.gtf_postprocess"
        conversions:
          - 'refflat'
          - gffutils: # kwargs below will be provided to `gffutils.create_db`
              merge_strategy: 'merge'
              id_spec:
                  transcript: ['transcript_id', 'transcript_symbol']
                  gene: ['gene_id', 'gene_symbol']
              gtf_transcript_key: 'transcript_id'
              gtf_gene_key: 'gene_id'
              disable_infer_genes: True

          # the attribute from the GTF to consider gene ID
          - genelist:
              gene_id: 'gene_id'

          - annotation_hub:
              ahkey: 'AH49581'
              keytype: 'ENSEMBL'

      fb_annotation:
        url: 'ftp://ftp.flybase.net/releases/FB2017_03/precomputed_files/genes/fbgn_annotation_ID.tsv.gz'
        postprocess: "lib.postprocess.dm6.fb_annotation_postprocess"

      fb_synonym:
        url: 'ftp://ftp.flybase.net/releases/FB2017_03/precomputed_files/synonyms/fb_synonym_fb_2017_03.tsv.gz'
        postprocess: "lib.postprocess.dm6.fb_synonym_postprocess"

      fasta:
        url: 'ftp://ftp.flybase.net/genomes/Drosophila_melanogaster/dmel_r6.16_FB2017_03/fasta/dmel-all-chromosome-r6.16.fasta.gz'
        postprocess: "lib.postprocess.dm6.fasta_postprocess"
        indexes:
          - 'bowtie2'
          - 'hisat2'

    r6-16_transcriptome:
      fasta:
        url: 'ftp://ftp.flybase.net/genomes/Drosophila_melanogaster/dmel_r6.16_FB2017_03/fasta/dmel-all-transcript-r6.16.fasta.gz'
        indexes:
          - 'kallisto'

    r6-16_and_ercc:
      gtf:
        url:
          - 'ftp://ftp.flybase.net/genomes/Drosophila_melanogaster/dmel_r6.16_FB2017_03/gtf/dmel-all-r6.16.gtf.gz'
          - 'https://www-s.nist.gov/srmors/certificates/documents/SRM2374_Sequence_v1.FASTA'
        postprocess:
          function: "lib.postprocess.merge.file_merge"
          args:
            - "lib.postprocess.dm6.gtf_postprocess"
            - "lib.postprocess.ercc.gtf_postprocess"
        conversions:
          - 'refflat'
          - 'gffutils'

      fasta:
        url:
          - 'ftp://ftp.flybase.net/genomes/Drosophila_melanogaster/dmel_r6.16_FB2017_03/fasta/dmel-all-chromosome-r6.16.fasta.gz'
          -  'https://www-s.nist.gov/srmors/certificates/documents/SRM2374_Sequence_v1.FASTA'
        postprocess:
          function: "lib.postprocess.merge.file_merge"
          args:
            - "lib.postprocess.dm6.fasta_postprocess"
            - "lib.postprocess.ercc.fasta_postprocess"
        indexes:
          - 'bowtie2'
          - 'hisat2'

  human:
    gencode-v25:
      fasta:
        url: 'ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_25/GRCh38.primary_assembly.genome.fa.gz'
        indexes:
          - 'hisat2'
          - 'bowtie2'
      gtf:
        url: 'ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_25/gencode.v25.annotation.gtf.gz'
        postprocess: 'lib.postprocess.hg38.strip_ensembl_version'
        conversions:
          - 'refflat'
          - gffutils:
              merge_strategy: 'merge'
              id_spec:
                  transcript: 'transcript_id'
                  gene: 'gene_id'
                  exon: 'exon_id'
              gtf_transcript_key: 'transcript_id'
              gtf_gene_key: 'gene_id'
              disable_infer_genes: True
              disable_infer_transcripts: True


    gencode-v25-transcriptome:
      fasta:
        url: 'ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_25/gencode.v25.transcripts.fa.gz'
        indexes:
          - 'kallisto'

    gencode-v19:
      fasta:
        url: 'ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_19/GRCh37.p13.genome.fa.gz'
        indexes:
          - 'bowtie2'
          - 'hisat2'
      gtf:
        url: 'ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_19/gencode.v19.annotation.gtf.gz'
        postprocess: 'lib.postprocess.hg38.strip_ensembl_version'
        conversions:
          - 'refflat'

    gencode_v19_plus_lncRNA_transcriptome:
      fasta:
        url:
          - 'ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_19/gencode.v19.pc_transcripts.fa.gz'
          - 'ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_19/gencode.v19.lncRNA_transcripts.fa.gz'
        postprocess: "lib.common.cat"
        indexes:
          - 'kallisto'

    rRNA:
      fasta:
        url:
          - 'https://www.arb-silva.de/fileadmin/silva_databases/release_128/Exports/SILVA_128_LSURef_tax_silva_trunc.fasta.gz'
          - 'https://www.arb-silva.de/fileadmin/silva_databases/release_128/Exports/SILVA_128_SSURef_Nr99_tax_silva_trunc.fasta.gz'
        postprocess:
            function: 'lib.common.filter_fastas'
            args: 'Homo sapiens'
        indexes:
            - 'hisat2'
            - 'bowtie2'

  mouse:
    gencode_m12:
      fasta:
        url: 'ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_mouse/release_M12/GRCm38.primary_assembly.genome.fa.gz'
        indexes:
          - 'hisat2'
          - 'bowtie2'
      gtf:
        url: 'ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_mouse/release_M12/gencode.vM12.annotation.gtf.gz'
        conversions:
          - 'refflat'


    gencode_m12_transcriptome:
      fasta:
        url: 'ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_mouse/release_M12/gencode.vM12.transcripts.fa.gz'
        indexes:
          - 'kallisto'
  ecoli:
    default:
      fasta:
        url: 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/845/GCF_000005845.2_ASM584v2/GCF_000005845.2_ASM584v2_genomic.fna.gz'
        indexes:
          - 'bowtie2'

  wolbachia:
    default:
      fasta:
        url: 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/008/025/GCF_000008025.1_ASM802v1/GCF_000008025.1_ASM802v1_genomic.fna.gz'
        indexes:
          - 'bowtie2'

  dicty:
    ensembl_2.7.33:
      gtf:
        url: 'ftp://ftp.ensemblgenomes.org/pub/release-33/protists/gtf/dictyostelium_discoideum/Dictyostelium_discoideum.dicty_2.7.33.gtf.gz'
        conversions:
          - 'refflat'

    ensembl_transcriptome_2.7:
      fasta:
        url:
            - "ftp://ftp.ensemblgenomes.org/pub/protists/release-33/fasta/dictyostelium_discoideum/cdna/Dictyostelium_discoideum.dicty_2.7.cdna.all.fa.gz"
            - "ftp://ftp.ensemblgenomes.org/pub/protists/release-33/fasta/dictyostelium_discoideum/ncrna/Dictyostelium_discoideum.dicty_2.7.ncrna.fa.gz"
        postprocess: "lib.common.cat"
        indexes:
            - "kallisto"

    ensembl_2.7:
      fasta:
        url: 'ftp://ftp.ensemblgenomes.org/pub/protists/release-33/fasta/dictyostelium_discoideum/dna/Dictyostelium_discoideum.dicty_2.7.dna_sm.toplevel.fa.gz'
        indexes:
            - 'bowtie2'
            - 'hisat2'
    rRNA:
      fasta:
        url:
            - 'https://www.arb-silva.de/fileadmin/silva_databases/release_128/Exports/SILVA_128_LSURef_tax_silva_trunc.fasta.gz'
            - 'https://www.arb-silva.de/fileadmin/silva_databases/release_128/Exports/SILVA_128_SSURef_Nr99_tax_silva_trunc.fasta.gz'
        indexes:
            - 'hisat2'
            - 'bowtie2'
        postprocess:
            function: 'lib.common.filter_fastas'
            args: 'Dictyostelium discoideum'

  phix:
    default:
      fasta:
        url: 'ftp://igenome:G3nom3s4u@ussd-ftp.illumina.com/PhiX/Illumina/RTA/PhiX_Illumina_RTA.tar.gz'
        postprocess: "lib.postprocess.phix.fasta_postprocess"
        indexes:
          - 'bowtie2'

  ercc:
    srm2374:
      fasta:
        url: 'https://www-s.nist.gov/srmors/certificates/documents/SRM2374_Sequence_v1.FASTA'
        postprocess: "lib.postprocess.ercc.fasta_postprocess"
        indexes:
          - 'bowtie2'
          - 'hisat2'
      gtf:
        url: 'https://www-s.nist.gov/srmors/certificates/documents/SRM2374_Sequence_v1.FASTA'
        postprocess: "lib.postprocess.ercc.gtf_postprocess"

    fisher92:
      fasta:
        url: 'https://tools.thermofisher.com/content/sfs/manuals/ERCC92.zip'
        postprocess: "lib.postprocess.erccFisher.fasta_postprocess"
        indexes:
          - 'bowtie2'
          - 'hisat2'
      gtf:
        url: 'https://tools.thermofisher.com/content/sfs/manuals/ERCC92.zip'
        postprocess: "lib.postprocess.erccFisher.gtf_postprocess"

  adapters:
    default:
      fasta:
        url: 'https://raw.githubusercontent.com/lcdb/lcdb-test-data/master/data/seq/adapters.fa'
        postprocess: "lib.postprocess.adapters.fasta_postprocess"
        indexes:
          - 'bowtie2'
